"""add db_type to connections

Revision ID: 543dc236aa2c
Revises: 6a58b53f7935
Create Date: 2025-12-26 14:38:45.521482

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '543dc236aa2c'
down_revision: Union[str, None] = '6a58b53f7935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Create the Enum type manually in the database
    db_type_enum = sa.Enum('postgresql', 'sqlserver', name='dbtype')
    db_type_enum.create(op.get_bind())

    # 2. Perform the autogenerated index cleanup
    op.drop_index(op.f('idx_backup_history_connection_id'), table_name='backup_history')
    op.drop_index(op.f('idx_backup_history_created_at'), table_name='backup_history')
    op.drop_index(op.f('idx_backup_history_status'), table_name='backup_history')
    op.drop_index(op.f('idx_backup_history_user_id'), table_name='backup_history')
    op.drop_index(op.f('idx_backup_schedules_connection_id'), table_name='backup_schedules')
    op.drop_index(op.f('idx_backup_schedules_user_id'), table_name='backup_schedules')
    
    # 3. Add the column using the now-existing type
    # Added server_default='postgresql' to avoid errors on existing rows
    op.add_column('database_connections', sa.Column('db_type', sa.Enum('postgresql', 'sqlserver', name='dbtype'), nullable=False, server_default='postgresql'))
    
    op.drop_index(op.f('idx_database_connections_user_id'), table_name='database_connections')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')

def downgrade() -> None:
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_database_connections_user_id'), 'database_connections', ['user_id'], unique=False)
    
    # 1. Drop the column
    op.drop_column('database_connections', 'db_type')
    
    # 2. Drop the Enum type from the database
    db_type_enum = sa.Enum('postgresql', 'sqlserver', name='dbtype')
    db_type_enum.drop(op.get_bind())

    op.create_index(op.f('idx_backup_schedules_user_id'), 'backup_schedules', ['user_id'], unique=False)
    op.create_index(op.f('idx_backup_schedules_connection_id'), 'backup_schedules', ['connection_id'], unique=False)
    op.create_index(op.f('idx_backup_history_user_id'), 'backup_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_backup_history_status'), 'backup_history', ['status'], unique=False)
    op.create_index(op.f('idx_backup_history_created_at'), 'backup_history', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_backup_history_connection_id'), 'backup_history', ['connection_id'], unique=False)